services:
  db:
    image: postgres:16
    container_name: yms_db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-yms}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-yms_password}
      POSTGRES_DB: ${POSTGRES_DB:-yms}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  # setup: # Раскомментируйте этот блок при первичном запуске на новом сервере для выполнения миграций и настройки базы данных.
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   environment:
  #     - POSTGRES_USER=yms
  #     - POSTGRES_PASSWORD=yms_password
  #     - POSTGRES_DB=yms
  #     - POSTGRES_HOST=db
  #     - POSTGRES_PORT=5432
  #     - PYTHONPATH=/app
  #   command: sh -c "python -m app.setup_database"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yms_backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      POSTGRES_USER: yms
      POSTGRES_PASSWORD: yms_password
      POSTGRES_DB: yms
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PYTHONPATH: /app
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backups:/app/backups
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yms_frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file: .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
volumes:
  db_data:
